version:  '3.4'
services:
        mysql:
            image: mysql:8.0
            restart: always
            command: --default-authentication-plugin=mysql_native_password
            #volumes:
            #    - ${DB_PATH_HOST}:/var/lib/mysql
            environment:
                MYSQL_ROOT_PASSWORD: "password"
            ports:
                - "3306:3306"
        nginx:
            image: nginx:1.19.0-alpine
            restart: on-failure
            volumes:
              - './public/:/usr/src/app'
              - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
            ports:
                - '80:80'
            depends_on:
                - php
        php:
            build:
              context: .
              dockerfile: docker/php/Dockerfile
            volumes:
              - './:/usr/src/app'
            restart: on-failure
            env_file:
              - .env
            user: 1000:1000
#volumes:
#  db-data: